package com.example.sneakersapp.model

data class Sneaker(
    val box_condition: String,
    val brand_name: String,
    val category: List<String>,
    val collection_slugs: List<String>,
    val color: String,
    val designer: String,
    val details: String,
    val gender: List<String>,
    val grid_picture_url: String,
    val has_picture: Boolean,
    val has_stock: Boolean,
    val id: Int,
    val keywords: List<String>,
    val main_picture_url: String,
    val midsole: String,
    val name: String,
    val nickname: String,
    val original_picture_url: String,
    val product_template_id: Int,
    val release_date: String,
    val release_date_unix: Int,
    val release_year: Int,
    val retail_price_cents: Int,
    val shoe_condition: String,
    val silhouette: String,
    val size_range: List<Double>,
    val sku: String,
    val slug: String,
    val status: String,
    val story_html: String,
    val upper_material: String
)